# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zach Herring Product Designer & Front End Developer
email: z.herring@gmail.com
description: > # this means to ignore newlines until "baseurl:"
     The portfolio of Zach Herring.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.zachherring.com/" # the base hostname & protocol for your site
twitter_username: zherring
github_username:  zherring

# Build settings
markdown: kramdown
exclude: ["/feed.xml"]
